/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorEditarProducto;
import javax.swing.JButton;

/**
 *
 * @author 1001001222
 */
public class AdminProductosForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminProductosForm
     */
    public AdminProductosForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        Ventas = new javax.swing.JCheckBox();
        Sucursal = new javax.swing.JCheckBox();
        Pais = new javax.swing.JCheckBox();
        Fechas = new javax.swing.JCheckBox();
        actualizad = new javax.swing.JButton();
        BD = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        btAgregar = new javax.swing.JButton();
        modoFacturas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        Ventas.setText("Ventas");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });

        Sucursal.setText("Sucursal");
        Sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucursalActionPerformed(evt);
            }
        });

        Pais.setText("País");
        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });

        Fechas.setText("Fechas");
        Fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechasActionPerformed(evt);
            }
        });

        actualizad.setText("Actualizar");

        BD.setText("BD");

        volver.setText("Volver");

        btAgregar.setText("Agregar");

        modoFacturas.setText("Modo facturas");
        modoFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Fechas)
                        .addGap(18, 18, 18)
                        .addComponent(Pais)
                        .addGap(18, 18, 18)
                        .addComponent(Ventas)
                        .addGap(18, 18, 18)
                        .addComponent(Sucursal)
                        .addGap(36, 36, 36)
                        .addComponent(modoFacturas)
                        .addGap(18, 18, 18)
                        .addComponent(actualizad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAgregar)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BD))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ventas)
                        .addComponent(Sucursal)
                        .addComponent(Pais)
                        .addComponent(Fechas)
                        .addComponent(actualizad)
                        .addComponent(modoFacturas))
                    .addComponent(btAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(volver)
                .addGap(36, 36, 36)
                .addComponent(BD))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasActionPerformed

    private void SucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SucursalActionPerformed

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

    private void FechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechasActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        
        int column = tablaProductos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablaProductos.getRowHeight();

        if(row<tablaProductos.getRowCount() && row >=0 && column < tablaProductos.getColumnCount() && column >=0){
                Object value=tablaProductos.getValueAt(row, column);
                if(value instanceof JButton){
                        ((JButton)value).doClick();
                        JButton boton = (JButton) value;

                        if(boton.getText().equals("Editar precio")){
                            System.out.println("--"+row+"--"+column);
                            System.out.println(tablaProductos.getValueAt(row, 0));
                            System.out.println("-----------");
                            EditarProductoForm vista=new EditarProductoForm();
        
                            ControladorEditarProducto controladorInicio=new ControladorEditarProducto(vista,tablaProductos.getValueAt(row, 0).toString(),Integer.parseInt(this.BD.getText()));
                            controladorInicio.vista.setVisible(true);
                            controladorInicio.vista.setLocationRelativeTo(null);
                            
                            this.dispose();
                        }
                }
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void modoFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modoFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProductosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BD;
    public javax.swing.JCheckBox Fechas;
    public javax.swing.JCheckBox Pais;
    public javax.swing.JCheckBox Sucursal;
    public javax.swing.JCheckBox Ventas;
    public javax.swing.JButton actualizad;
    public javax.swing.JButton btAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JCheckBox modoFacturas;
    public javax.swing.JTable tablaProductos;
    public javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
