/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import controlador.ControladorEditarProducto;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author 1001001222
 */
public class CompraProductosForm extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaProductosForm
     */
    public CompraProductosForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        productos = new javax.swing.JComboBox<>();
        btConsultar = new javax.swing.JButton();
        btVolver = new javax.swing.JButton();
        BD = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        metodoPago = new javax.swing.JComboBox<>();
        envio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        btComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btConsultar.setText("Consultar");

        btVolver.setText("Volver");

        metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de crédito" }));

        envio.setText("Envio");

        jLabel1.setText("Cantidad");

        btComentar.setText("Comentar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btVolver))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btComentar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(envio)
                        .addGap(80, 80, 80)
                        .addComponent(btConsultar)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar)
                    .addComponent(metodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(envio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btComentar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btVolver)
                                .addGap(11, 11, 11))
                            .addComponent(BD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        try{
            int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
            int row = evt.getY()/tabla.getRowHeight();
            

            if(row<tabla.getRowCount() && row >=0 && column < tabla.getColumnCount() && column >=0){
                    Object value=tabla.getValueAt(row, column);
                    if(value instanceof JButton){
                            ((JButton)value).doClick();
                            JButton boton = (JButton) value;

                            if(boton.getText().equals("Comprar")){
                                int cantidadAComprar=Integer.parseInt(cantidad.getText());
                                int enviar=0;
                                if(envio.isSelected()){
                                    enviar=1;
                                }
                                
                                System.out.println("COMPRAR--"+row+"--"+column);
                                System.out.println(tabla.getValueAt(row, 0));
                                System.out.println(tabla.getValueAt(row, 2));
                                System.out.println(tabla.getValueAt(row, 3));
                                System.out.println("-----------"+this.client.getText().toString());
                                
                                Conexion conexion=new Conexion();
                                Connection con=conexion.conectar(Integer.parseInt(this.BD.getText()));
                                //Statement stmt = con.createStatement();

                                CallableStatement param;
                                param = con.prepareCall("{call insertarFacturaTemp(?,?,?,?,?,?,?)}");
                                param.setString(1, this.client.getText().toString());
                                
                                String suc=tabla.getValueAt(row, 2).toString();
                                suc=suc.substring(suc.length()-1, suc.length());
                                param.setInt(2, Integer.parseInt(suc));
                                
                                //param.setInt(2, row+1);
                                param.setInt(3, enviar);
                                param.setString(4, tabla.getValueAt(row, 0).toString());
                                param.setInt(5, cantidadAComprar);
                                param.setFloat(6, Float.parseFloat(tabla.getValueAt(row, 3).toString()));
                                param.setInt(7, this.metodoPago.getSelectedIndex()+1);
                                param.executeUpdate();
                                JOptionPane.showMessageDialog(this, "Bebidas comprada con éxito");
                                /*EditarProductoForm vista=new EditarProductoForm();

                                ControladorEditarProducto controladorInicio=new ControladorEditarProducto(vista,tabla.getValueAt(row, 0).toString(),Integer.parseInt(this.BD.getText()));
                                controladorInicio.vista.setVisible(true);
                                controladorInicio.vista.setLocationRelativeTo(null);

                                this.dispose();*/
                                conexion.CerrarConexion(con);
                            }else if(boton.getText().equals("Ver")){
                                System.out.println("VER--"+row+"--"+column);
                                System.out.println(tabla.getValueAt(row, 0));
                                System.out.println("-----------");

                                /*EditarProductoForm vista=new EditarProductoForm();

                                ControladorEditarProducto controladorInicio=new ControladorEditarProducto(vista,tabla.getValueAt(row, 0).toString(),Integer.parseInt(this.BD.getText()));
                                controladorInicio.vista.setVisible(true);
                                controladorInicio.vista.setLocationRelativeTo(null);

                                this.dispose();*/
                            }
                    }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No hay stock");
            System.out.println("ERROR: "+ex);
        }
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraProductosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraProductosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BD;
    public javax.swing.JButton btComentar;
    public javax.swing.JButton btConsultar;
    public javax.swing.JButton btVolver;
    public javax.swing.JTextField cantidad;
    public javax.swing.JLabel client;
    public javax.swing.JCheckBox envio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> metodoPago;
    public javax.swing.JComboBox<String> productos;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
