/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Factura;

/**
 *
 * @author 1001001222
 */
public class FacturaForm extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaProductosForm
     */
    public FacturaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btVolver = new javax.swing.JButton();
        BD = new javax.swing.JLabel();
        refrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btVolver.setText("Volver");
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });

        refrescar.setText("Refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refrescar)
                        .addGap(18, 18, 18)
                        .addComponent(btVolver)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVolver)
                    .addComponent(refrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        try{
            int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
            int row = evt.getY()/tabla.getRowHeight();
            

            if(row<tabla.getRowCount() && row >=0 && column < tabla.getColumnCount() && column >=0){
                    Object value=tabla.getValueAt(row, column);
                    if(value instanceof JButton){
                            ((JButton)value).doClick();
                            JButton boton = (JButton) value;

                            if(boton.getText().equals("Facturar")){
                                System.out.println("COMPRAR--"+row+"--"+column);
                                System.out.println(tabla.getValueAt(row, 0));
                                System.out.println(tabla.getValueAt(row, 2));
                                System.out.println(tabla.getValueAt(row, 3));
                                
                                Conexion conexion=new Conexion();
                                Connection con=conexion.conectar(Integer.parseInt(this.BD.getText()));
                                //Statement stmt = con.createStatement();

                                CallableStatement param;
                                param = con.prepareCall("{call getCant(?,?)}");
                                param.setString(1, tabla.getValueAt(row, 5).toString());
                                
                                String suc=tabla.getValueAt(row, 3).toString();
                                suc=suc.substring(suc.length()-1, suc.length());
                                param.setInt(2, Integer.parseInt(suc));
                                
                                ResultSet rs=param.executeQuery();
                                int cantidad=0;
                                while (rs.next()) {
                                    cantidad=rs.getInt(1);
                                       //System.out.println("AAAAA:"+rs.getString(1));
                                }
                                rs.close();
                                conexion.CerrarConexion(con);
                                System.out.println("COMPARACION: "+Integer.toString(cantidad)+"--"+tabla.getValueAt(row, 6).toString());
                                if(cantidad>Integer.parseInt(tabla.getValueAt(row, 6).toString())){
                                    Conexion conexion2=new Conexion();
                                    Connection con2=conexion2.conectar(Integer.parseInt(this.BD.getText()));
                                    //Statement stmt = con.createStatement();

                                    CallableStatement param2;
                                    param2 = con2.prepareCall("{call Facturacion(?)}");
                                    param2.setInt(1, Integer.parseInt(tabla.getValueAt(row, 0).toString()));
                                    
                                    param2.executeUpdate();
                                    
                                    conexion2.CerrarConexion(con2);
                                    
                                    JOptionPane.showMessageDialog(this, "Facturación éxitosa");
                                }else{
                                    JOptionPane.showMessageDialog(this, "No hay stock");
                                }
                                
                                
                                /*EditarProductoForm vista=new EditarProductoForm();

                                ControladorEditarProducto controladorInicio=new ControladorEditarProducto(vista,tabla.getValueAt(row, 0).toString(),Integer.parseInt(this.BD.getText()));
                                controladorInicio.vista.setVisible(true);
                                controladorInicio.vista.setLocationRelativeTo(null);

                                this.dispose();*/
                                
                            }else if(boton.getText().equals("Ver")){
                                System.out.println("VER--"+row+"--"+column);
                                System.out.println(tabla.getValueAt(row, 0));
                                System.out.println("-----------");

                                /*EditarProductoForm vista=new EditarProductoForm();

                                ControladorEditarProducto controladorInicio=new ControladorEditarProducto(vista,tabla.getValueAt(row, 0).toString(),Integer.parseInt(this.BD.getText()));
                                controladorInicio.vista.setVisible(true);
                                controladorInicio.vista.setLocationRelativeTo(null);

                                this.dispose();*/
                            }
                    }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error: No hay stock");
            System.out.println("ERROR: "+ex);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVolverActionPerformed

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BD;
    public javax.swing.JButton btVolver;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton refrescar;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
